Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "centos/6"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "ansible" do |ansible|
    ansible.extra_vars = {
       name: "pure-ftpd",
    }
    ansible.playbook = "playbook.yml"
  end
end